import random


dictionary = {'Alabama': 'Montgomery',
    'Alaska': 'Juneau',
    'Arizona':'Phoenix',
    'Arkansas':'Little Rock',
    'California': 'Sacramento',
    'Colorado':'Denver',
    'Connecticut':'Hartford',
    'Delaware':'Dover',
    'Florida': 'Tallahassee',
    'Georgia': 'Atlanta',
    'Hawaii': 'Honolulu',
    'Idaho': 'Boise',
    'Illinios': 'Springfield',
    'Indiana': 'Indianapolis',
    'Iowa': 'Des Monies',
    'Kansas': 'Topeka',
    'Kentucky': 'Frankfort',
    'Louisiana': 'Baton Rouge',
    'Maine': 'Augusta',
    'Maryland': 'Annapolis',
    'Massachusetts': 'Boston',
    'Michigan': 'Lansing',
    'Minnesota': 'St. Paul',
    'Mississippi': 'Jackson',
    'Missouri': 'Jefferson City',
    'Montana': 'Helena',
    'Nebraska': 'Lincoln',
    'Neveda': 'Carson City',
    'New Hampshire': 'Concord',
    'New Jersey': 'Trenton',
    'New Mexico': 'Santa Fe',
    'New York': 'Albany',
    'North Carolina': 'Raleigh',
    'North Dakota': 'Bismarck',
    'Ohio': 'Columbus',
    'Oklahoma': 'Oklahoma City',
    'Oregon': 'Salem',
    'Pennsylvania': 'Harrisburg',
    'Rhoda Island': 'Providence',
    'South Carolina': 'Columbia',
    'South Dakoda': 'Pierre',
    'Tennessee': 'Nashville',
    'Texas': 'Austin',
    'Utah': 'Salt Lake City',
    'Vermont': 'Montpelier',
    'Virginia': 'Richmond',
    'Washington': 'Olympia',
    'West Virginia': 'Charleston',
    'Wisconsin': 'Madison',
    'Wyoming': 'Cheyenne' }

for quiz in range(35):
  f = open(f'quiz{quiz+1}.txt', 'w+')
  keys = list(dictionary.keys())
  capitals = list(dictionary.values())
  answerKey = []
  random.shuffle(keys)
  shuffledDict = dict()
  
  for key in keys:
    shuffledDict.update({key: dictionary[key]})
  
  
  for key in shuffledDict:
    f.write("What is the state capital of "+key+"?\n")
    key1 = random.choice(capitals)
    key2 = random.choice(capitals)
    key3 = random.choice(capitals)
    if key1 == key2 or key3 or shuffledDict[key]:
      key1 = random.choice(capitals)
    if key2 == key1 or key3 or shuffledDict[key]:
      key2 = random.choice(capitals)
    if key3 == key2 or key1 or shuffledDict[key]:
      key3 = random.choice(capitals)
    answers = [key1, key2, key3, shuffledDict[key]]
    random.shuffle(answers)
    for x in range(len(answers)):
      f.write(answers[x]+'\n')
    answerKey.append(shuffledDict[key])
  
  f.close()
  
  o = open(f'answers{quiz+1}.txt', 'w+')
  for x in range(len(answerKey)):
    o.write(answerKey[x]+'\n')
  
  
  
  o.close()

